---
apache::package_ensure: present
apache::port: 80
apache::secret: ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAG4SmCJVM3Rch7t6uxrg1EREZ3tPkPYa1o7pa1qHTVic84cakvmvx7ZtIjIgMA7/f/4uM2NWfUkB2+3ILA8yQS1bcdjoP12FYw8zlrfPr+A++aAdpoxajc72mnRwcUpfMd4TlPSBSm/ZGkIBh9kT8bXhuA1QzeieAQqKWxl+EVzi9t4sr7kEh39KR3139vdSc1rOSYjGGCO36rUorr+PaA9XhtgDA786FwuTcuO+5Mdbxvfrgz7u5OLXPy1OcJMS1EeseMD3KyUIq5ccI8lp2JKFu5kCZdN6smTpM9sZ1xD19zs7wqp3TfSzDxk4acm0EXqRPCapjjw/k3tegTLk0uDA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBCeOT2KV/TB2Y53zk8GXtE4gBB1KveEKSoQ4Jhdc7jCFw3o]
apache::service_ensure: running
classes:
- apache
- postgresql
postgresql::package_ensure: present
postgresql::package_name: postgresql
postgresql::password: ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAairPVoFGTE/ByhgqQPeS86WjpMjQpqDw4pZMhzMYTdb3JmdCegKGNeuFoS5gN+r7cHxmEWUiV9tTmhfVWC+M2Do0e0uKmNNEfx5PnAxmyuM/BVXQuTl8BpB4H7Ho22xWDLMLfvG1HkYGudopMCx6eyUsGfDsp+GWWGMmYqsF500AATECJXn878UYVcnxQKesGqB2s7bMG2wjcUg1eA7uEF+x+JY/yZCHkySGp7oopLkfVJ12J9ognW8c2oSXXsDDkoQOdCi35J33FgL8URvXOBtAhLmpz5hbJCflV3vlz8zvLrCLAyaDkO7u0YFO3d3Ef6k8hLBU+dMxmsmL9UokljA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBBCbd6GpoLb1JUuhAYFvslfgBDQKBave5pn4EMXNE6kWrFD]
postgresql::service_enabled: true
