---
apache::package_ensure: present
apache::port: 80
apache::secret: ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAiHaYBUU3KIHVbus/OsoQa3zHsHtmQpfY4TqQYFZfMabC/xQPcTi7Awzb9XA+7+gqwuZdJEH594efe9bsIbkuo0REEjIv2TkUl5y3EKilYshdXbnk4SQS6YyJE07RcvW3fwEvaAWth28lgidx/VVi8ofYVlfDAwWqI7tpWXMJgDA79ZKSvtiYaIWoBUKZs+0DjPSSHUwiAJxbhOAZRymD4KOg/aIvqwFXh9gWHv6JUf+7mDwHo1sFHgf+RCDh8jaA1tZvyFmHlJncpy2PdrMqIFRRlz1w6dFegNjsqI0Cnuv8mIpfvFZcrgOaIg9LabU+PY6T2vKNZVeFdH6vWEVY7DA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBCm3UFenVWQ7LKrzYj713yfgBBciBOCJwmChrS8/222YlzK]
apache::service_ensure: running
classes:
- apache
