---
apache::package_ensure: present
apache::port: 80
apache::secret: ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAkmGDrHkCcoa91V1khuPFIGO7O/rveRiN6aXGIbeQXRw4abGTSyO5SWc8Txk2Ty6RWXTX2kWABwHh6Dzo+Ak9IGS+aayjlq/c8VVE6I6BrbXH0g+6QJ7HOD/wQqHDowpIsIbNlTR8am0MFq9tXCVyAj3wmJYMnqSXUZJcyEIZh4xNqdDzbH2Dixe6MOdY5/lg1MlKpdwZoayFdoVCEt8q2ItbFyeX/0hjh0VDZ7gjvkn8nsspMwNazw/JPHwazVJfdZeZ5Wh/Qzro4whCuJjQSpEYHxYd2qYTsoImLD70Um7LFyntWj4Lp+S0FAYTDWRzfkolG60kuMXmRoHgRDK9PzA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBC12DBY76aVrR9okXFSwSl4gBAmWFS28772rsepK9donbzw]
apache::service_ensure: running
classes:
- apache
- postgresql
postgresql::package_ensure: present
postgresql::package_name: postgresql
postgresql::password: ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAbQ3+xxw1mxShcoapVDemmDBAT9+OZTKP1ohnuYIo4fHYg5JeYdI3MsfTiEUIdkm7Wt+CrUh63soW0HRzLcaIF7cTfYOZfDeRIFLRCESus15n1dTYIyjERPgvTFkBNIVv9u0u9JnyPfI2KWZruErWccklTGuaZe60ztrCIBMw9cOXzgccfRMbYlJp0bH9uwzfOV6LlVJKUdjiKyBOzZXQB0tgrG5fClOvKkaCIRQY2Ynhr+QRAjdWQxTmV0WgEBBK9uSMBdpFHWazggKgpPW0fwAhmcE3bPYQ01WIegilPxJ6LrgijQW64QeCaHwhDsv1r6ORCpzunyXCQIy3/t25gDA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBBW4wK0Q7hWktvXhfoAe+eggBDH9PvYldRKcJZkkss8yHPg]
postgresql::service_enabled: true
