---
apache::package_ensure: present
apache::password: ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAgUR4OuOD0Vxozp5It9aRFZqkDY4wHCUzcrKa44+22MMZzwucG6VvZpNSjUbH8rT6lqNT2PJwgeBYzYR3crUxFia57tir3R94i3i4RQMng9k/YR8Io+MaQyAxVo5waxTB+z7E0Eg3PDP6oo7mCptv3fE2S5sZoDGQQHlVq1qCHxIyiF+HN3u1Rz/w6z3vldMA+0eJFTOtZFg1DmumSFnxzePw8czXnA2jqUTjp/Vw7k3HV721dUBPJYkitoafnOr+rAeujNEpB3WCjBMbqnhXmS6n7PBvuWZeGAPG81UN0aCUARfQR1meeycA4N29vJWJ2A5aEwcKSc+1D3hRaSNa3TBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBCZZdXd4T9Exqk5mB08TYGugCAEw0JDlgxy+Y37e5oQZxHZCXetcewtPYYbKaXMmNzmqA==]
apache::port: 8008
apache::service_ensure: running
classes:
- apache
- ntp
- mysql
mysql::package_ensure: present
mysql::package_name: mysql-server
mysql::service_enabled: true
ntp::package_ensure: present
ntp::servers: ntp.ubuntu.com
