---
apache::package_ensure: absent
apache::port: 80
apache::service_ensure: running
classes:
- apache
- postgresql
postgresql::package_ensure: present
postgresql::package_name: postgresql
postgresql::password: ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAlm7Bc8KM/SA/MhGhLXrNKUjsppHmPVBIjokVmhyWAjgasj8EKQabxhEj74ULlB7yysVskZBTgFxydfX30h8S46iYs1RnsXjvsnB2dOToP98duW/vYvxpKf9hXtQnHB4dB+dotm+elsi74hEukfZLaQVq9pTOICCgnaFzjDL28A1lTEqWxxvGaT8DiDvFFftHn92wkpilm4Frzk55YbYnRrKwuBrNRKA6vbcgNp/CwoMq/KyutF7kC4sDdQ1xyRfV0E2XXe6YyJL1JV36z6Vh0V13QaNPv/vIcDRrXo8zc2zVCaTsLdc9JFvD8XMobFpMb8AmrxAF/OjPPcEFEGrSpTA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBCo6BR9PwL2nEu3b5hvqil1gBB4o6y61KC2U/8P8nTvSKWs]
postgresql::service_enabled: true
