---
apache::package_ensure: absent
apache::port: 80
apache::service_ensure: running
classes:
- apache
- mysql
mysql::package_ensure: present
mysql::package_name: mysql-server
mysql::service_enabled: true
